var groceries = [
        {value: 'air freshener'},
        {value: 'aluminum foil'},
        {value: 'apples'},
        {value: 'applesauce'},
        {value: 'apricots'},
        {value: 'artichokes'},
        {value: 'asparagus'},
        {value: 'avocados'},
        {value: 'baby cereal'},
        {value: 'baby food'},
        {value: 'bacon'},
        {value: 'bagels'},
        {value: 'baked beans'},
        {value: 'baking powder'},
        {value: 'baking soda'},
        {value: 'bananas'},
        {value: 'basil'},
        {value: 'basil'},
        {value: 'bath soap'},
        {value: 'batteries'},
        {value: 'bay leaves'},
        {value: 'bbq sauce'},
        {value: 'bbq seasoning'},
        {value: 'beer'},
        {value: 'beets'},
        {value: 'berries'},
        {value: 'biscuits'},
        {value: 'black beans'},
        {value: 'bleach'},
        {value: 'bread'},
        {value: 'bread crumbs'},
        {value: 'broccoli'},
        {value: 'broth'},
        {value: 'brown rice'},
        {value: 'bug repellant'},
        {value: 'bullion cubes'},
        {value: 'burger helper'},
        {value: 'butter'},
        {value: 'cabbage'},
        {value: 'cake'},
        {value: 'cake decor'},
        {value: 'cake mix'},
        {value: 'candy'},
        {value: 'canned fruit'},
        {value: 'canned milk'},
        {value: 'canned vegetables'},
        {value: 'carrots'},
        {value: 'carrots'},
        {value: 'cat food'},
        {value: 'cat sand'},
        {value: 'catfish'},
        {value: 'catsup'},
        {value: 'cauliflower'},
        {value: 'celery'},
        {value: 'cereal'},
        {value: 'champagne'},
        {value: 'charcoal'},
        {value: 'cheddar cheese'},
        {value: 'cherries'},
        {value: 'chicken'},
        {value: 'chicken bites'},
        {value: 'chiles'},
        {value: 'chili'},
        {value: 'chives'},
        {value: 'chocolate chips'},
        {value: 'cilantro'},
        {value: 'cinnamon'},
        {value: 'cloves'},
        {value: 'club soda'},
        {value: 'cocktail sauce'},
        {value: 'cocoa'},
        {value: 'cod'},
        {value: 'coffee'},
        {value: 'coffee filters'},
        {value: 'conditioner'},
        {value: 'cookies'},
        {value: 'cookies'},
        {value: 'cooking spray'},
        {value: 'corn'},
        {value: 'corn'},
        {value: 'cornmeal'},
        {value: 'cornstarch'},
        {value: 'cotton swabs'},
        {value: 'couscous'},
        {value: 'crab'},
        {value: 'crackers'},
        {value: 'cream'},
        {value: 'cream cheese'},
        {value: 'creamed corn'},
        {value: 'croutons'},
        {value: 'cucumbers'},
        {value: 'cumin'},
        {value: 'cups'},
        {value: 'curry'},
        {value: 'deli meat'},
        {value: 'dental floss'},
        {value: 'deodorant'},
        {value: 'desserts'},
        {value: 'diaper cream'},
        {value: 'diapers'},
        {value: 'diet soft drinks'},
        {value: 'dill'},
        {value: 'dinner rolls'},
        {value: 'dip'},
        {value: 'dish soap'},
        {value: 'dishwasher detergent'},
        {value: 'dog food'},
        {value: 'donuts'},
        {value: 'dried fruit'},
        {value: 'egg substitute'},
        {value: 'eggplant'},
        {value: 'eggs'},
        {value: 'elbow macaroni'},
        {value: 'energy drinks'},
        {value: 'fabric softener'},
        {value: 'facial tissue'},
        {value: 'family planning'},
        {value: 'feminine products'},
        {value: 'feta cheese'},
        {value: 'fish sticks'},
        {value: 'flea treatment'},
        {value: 'floor cleaner'},
        {value: 'flour'},
        {value: 'food coloring'},
        {value: 'formula'},
        {value: 'frosting'},
        {value: 'fruit'},
        {value: 'fruit snacks'},
        {value: 'garbage bags'},
        {value: 'garlic cloves'},
        {value: 'garlic powder'},
        {value: 'garlic salt'},
        {value: 'gelatin'},
        {value: 'glass spray'},
        {value: 'graham crackers'},
        {value: 'granola bars'},
        {value: 'grapefruit'},
        {value: 'grapes'},
        {value: 'gravy mix'},
        {value: 'green onions'},
        {value: 'greeting cards'},
        {value: 'grits'},
        {value: 'ground beef'},
        {value: 'ground turkey'},
        {value: 'gum'},
        {value: 'hair spray'},
        {value: 'half & half'},
        {value: 'halibut'},
        {value: 'ham'},
        {value: 'hamburger buns'},
        {value: 'hand soap'},
        {value: 'honey'},
        {value: 'horseradish'},
        {value: 'hot dog buns'},
        {value: 'hot dogs'},
        {value: 'hot sauce'},
        {value: 'ice'},
        {value: 'ice cream'},
        {value: 'ice pops'},
        {value: 'instant breakfast drink'},
        {value: 'Italian seasoning'},
        {value: 'jack cheese'},
        {value: 'jam/jelly'},
        {value: 'juice'},
        {value: 'juice'},
        {value: 'kiwi'},
        {value: 'lasagna'},
        {value: 'laundry soap'},
        {value: 'lemon juice'},
        {value: 'lemons'},
        {value: 'lettuce'},
        {value: 'light bulbs'},
        {value: 'limes'},
        {value: 'lip care'},
        {value: 'liquor'},
        {value: 'lobster'},
        {value: 'lotion'},
        {value: 'mac & cheese'},
        {value: 'makeup'},
        {value: 'marinade'},
        {value: 'mayonnaise'},
        {value: 'meat'},
        {value: 'meat tenderizer'},
        {value: 'melons'},
        {value: 'milk'},
        {value: 'mouthwash'},
        {value: 'mozarella'},
        {value: 'muffin mix'},
        {value: 'muffins'},
        {value: 'mushrooms'},
        {value: 'mustard'},
        {value: 'napkins'},
        {value: 'nectarines'},
        {value: 'noodle mix'},
        {value: 'nuts'},
        {value: 'oatmeal'},
        {value: 'olive oil'},
        {value: 'olives (black)'},
        {value: 'olives (green)'},
        {value: 'onions'},
        {value: 'oranges'},
        {value: 'oregano'},
        {value: 'oysters'},
        {value: 'pancake mix'},
        {value: 'papaya'},
        {value: 'paper plates'},
        {value: 'paper towels'},
        {value: 'paprika'},
        {value: 'pasta'},
        {value: 'pasta sauce'},
        {value: 'pastries'},
        {value: 'peaches'},
        {value: 'peanut butter'},
        {value: 'pears'},
        {value: 'pepper'},
        {value: 'peppers'},
        {value: 'pickles'},
        {value: 'pie'},
        {value: 'pie crust'},
        {value: 'pie filling'},
        {value: 'pie shells'},
        {value: 'pita bread'},
        {value: 'pizza'},
        {value: 'plastic bags'},
        {value: 'plastic cutlery'},
        {value: 'plastic wrap'},
        {value: 'plums'},
        {value: 'polish'},
        {value: 'pomegranate'},
        {value: 'popcorn'},
        {value: 'poppy seed'},
        {value: 'pork'},
        {value: 'pot pies'},
        {value: 'potato chips'},
        {value: 'potatoes'},
        {value: 'potatoes'},
        {value: 'pretzels'},
        {value: 'processed cheese'},
        {value: 'pudding'},
        {value: 'raisins'},
        {value: 'razors/blades'},
        {value: 'red pepper'},
        {value: 'relish'},
        {value: 'rice mix'},
        {value: 'sage'},
        {value: 'salad dressing'},
        {value: 'salad greens'},
        {value: 'salmon'},
        {value: 'salsa'},
        {value: 'salsa'},
        {value: 'salt'},
        {value: 'sausage'},
        {value: 'seasoned salt'},
        {value: 'seeds'},
        {value: 'shampoo'},
        {value: 'shampoo'},
        {value: 'shaving cream'},
        {value: 'shortening'},
        {value: 'shredded cheese'},
        {value: 'shrimp'},
        {value: 'soft drinks'},
        {value: 'soup'},
        {value: 'soup mix'},
        {value: 'sour cream'},
        {value: 'soy sauce'},
        {value: 'spaghetti'},
        {value: 'spinach'},
        {value: 'sponges'},
        {value: 'sprouts'},
        {value: 'squash'},
        {value: 'steak'},
        {value: 'steak sauce'},
        {value: 'straws'},
        {value: 'sugar'},
        {value: 'sugar (brown)'},
        {value: 'sugar (powdered)'},
        {value: 'sunscreen'},
        {value: 'sweet & sour'},
        {value: 'swiss cheese'},
        {value: 'tea'},
        {value: 'teriyaki'},
        {value: 'tilapia'},
        {value: 'toilet tissue'},
        {value: 'tomatoes'},
        {value: 'toothbrush'},
        {value: 'toothpaste'},
        {value: 'tortilla chips'},
        {value: 'tortillas (corn)'},
        {value: 'tortillas (flour)'},
        {value: 'treats'},
        {value: 'tuna'},
        {value: 'turkey'},
        {value: 'tv dinners'},
        {value: 'vacuum bags'},
        {value: 'vanilla extract'},
        {value: 'vegetable oil'},
        {value: 'vegetables'},
        {value: 'veggieburger'},
        {value: 'vinegar'},
        {value: 'waffles'},
        {value: 'watermelon'},
        {value: 'waxed paper'},
        {value: 'whipped cream'},
        {value: 'white rice'},
        {value: 'wine'},
        {value: 'wipes'},
        {value: 'yeast'},
        {value: 'yogurt'},
        {value: 'zucchini'},
];
