var groceries = [
        {value: 'Air freshener'},
        {value: 'Aluminum foil'},
        {value: 'Apples'},
        {value: 'Applesauce'},
        {value: 'Apricots'},
        {value: 'Artichokes'},
        {value: 'Asparagus'},
        {value: 'Avocados'},
        {value: 'Baby cereal'},
        {value: 'Baby food'},
        {value: 'Bacon'},
        {value: 'Bagels'},
        {value: 'Baked beans'},
        {value: 'Baking powder'},
        {value: 'Baking soda'},
        {value: 'Bananas'},
        {value: 'Basil'},
        {value: 'Basil'},
        {value: 'Bath soap'},
        {value: 'Batteries'},
        {value: 'Bay leaves'},
        {value: 'Bbq sauce'},
        {value: 'Bbq seasoning'},
        {value: 'Beer'},
        {value: 'Beets'},
        {value: 'Berries'},
        {value: 'Biscuits'},
        {value: 'Black beans'},
        {value: 'Bleach'},
        {value: 'Bread'},
        {value: 'Bread crumbs'},
        {value: 'Broccoli'},
        {value: 'Broth'},
        {value: 'Brown rice'},
        {value: 'Bug repellant'},
        {value: 'Bullion cubes'},
        {value: 'Burger helper'},
        {value: 'Butter'},
        {value: 'Cabbage'},
        {value: 'Cake'},
        {value: 'Cake decor'},
        {value: 'Cake mix'},
        {value: 'Candy'},
        {value: 'Canned fruit'},
        {value: 'Canned milk'},
        {value: 'Canned vegetables'},
        {value: 'Carrots'},
        {value: 'Carrots'},
        {value: 'Cat food'},
        {value: 'Cat sand'},
        {value: 'Catfish'},
        {value: 'Catsup'},
        {value: 'Cauliflower'},
        {value: 'Celery'},
        {value: 'Cereal'},
        {value: 'Champagne'},
        {value: 'Charcoal'},
        {value: 'Cheddar cheese'},
        {value: 'Cherries'},
        {value: 'Chicken'},
        {value: 'Chicken bites'},
        {value: 'Chiles'},
        {value: 'Chili'},
        {value: 'Chives'},
        {value: 'Chocolate chips'},
        {value: 'Cilantro'},
        {value: 'Cinnamon'},
        {value: 'Cloves'},
        {value: 'Club soda'},
        {value: 'Cocktail sauce'},
        {value: 'Cocoa'},
        {value: 'Cod'},
        {value: 'Coffee'},
        {value: 'Coffee filters'},
        {value: 'Conditioner'},
        {value: 'Cookies'},
        {value: 'Cookies'},
        {value: 'Cooking spray'},
        {value: 'Corn'},
        {value: 'Corn'},
        {value: 'Cornmeal'},
        {value: 'Cornstarch'},
        {value: 'Cotton swabs'},
        {value: 'Couscous'},
        {value: 'Crab'},
        {value: 'Crackers'},
        {value: 'Cream'},
        {value: 'Cream cheese'},
        {value: 'Creamed corn'},
        {value: 'Croutons'},
        {value: 'Cucumbers'},
        {value: 'Cumin'},
        {value: 'Cups'},
        {value: 'Curry'},
        {value: 'Deli meat'},
        {value: 'Dental floss'},
        {value: 'Deodorant'},
        {value: 'Desserts'},
        {value: 'Diaper cream'},
        {value: 'Diapers'},
        {value: 'Diet soft drinks'},
        {value: 'Dill'},
        {value: 'Dinner rolls'},
        {value: 'Dip'},
        {value: 'Dish soap'},
        {value: 'Dishwasher detergent'},
        {value: 'Dog food'},
        {value: 'Donuts'},
        {value: 'Dried fruit'},
        {value: 'Egg substitute'},
        {value: 'Eggplant'},
        {value: 'Eggs'},
        {value: 'Elbow macaroni'},
        {value: 'Energy drinks'},
        {value: 'Fabric softener'},
        {value: 'Facial tissue'},
        {value: 'Family planning'},
        {value: 'Feminine products'},
        {value: 'Feta cheese'},
        {value: 'Fish sticks'},
        {value: 'Flea treatment'},
        {value: 'Floor cleaner'},
        {value: 'Flour'},
        {value: 'Food coloring'},
        {value: 'Formula'},
        {value: 'Frosting'},
        {value: 'Fruit'},
        {value: 'Fruit snacks'},
        {value: 'Garbage bags'},
        {value: 'Garlic cloves'},
        {value: 'Garlic powder'},
        {value: 'Garlic salt'},
        {value: 'Gelatin'},
        {value: 'Glass spray'},
        {value: 'Graham crackers'},
        {value: 'Granola bars'},
        {value: 'Grapefruit'},
        {value: 'Grapes'},
        {value: 'Gravy mix'},
        {value: 'Green onions'},
        {value: 'Greeting cards'},
        {value: 'Grits'},
        {value: 'Ground beef'},
        {value: 'Ground turkey'},
        {value: 'Gum'},
        {value: 'Hair spray'},
        {value: 'Half & half'},
        {value: 'Halibut'},
        {value: 'Ham'},
        {value: 'Hamburger buns'},
        {value: 'Hand soap'},
        {value: 'Honey'},
        {value: 'Horseradish'},
        {value: 'Hot dog buns'},
        {value: 'Hot dogs'},
        {value: 'Hot sauce'},
        {value: 'Ice'},
        {value: 'Ice cream'},
        {value: 'Ice pops'},
        {value: 'Instant breakfast drink'},
        {value: 'Italian seasoning'},
        {value: 'Jack cheese'},
        {value: 'Jam/jelly'},
        {value: 'Juice'},
        {value: 'Juice'},
        {value: 'Kiwi'},
        {value: 'Lasagna'},
        {value: 'Laundry soap'},
        {value: 'Lemon juice'},
        {value: 'Lemons'},
        {value: 'Lettuce'},
        {value: 'Light bulbs'},
        {value: 'Limes'},
        {value: 'Lip care'},
        {value: 'Liquor'},
        {value: 'Lobster'},
        {value: 'Lotion'},
        {value: 'Mac & cheese'},
        {value: 'Makeup'},
        {value: 'Marinade'},
        {value: 'Mayonnaise'},
        {value: 'Meat'},
        {value: 'Meat tenderizer'},
        {value: 'Melons'},
        {value: 'Milk'},
        {value: 'Mouthwash'},
        {value: 'Mozarella'},
        {value: 'Muffin mix'},
        {value: 'Muffins'},
        {value: 'Mushrooms'},
        {value: 'Mustard'},
        {value: 'Napkins'},
        {value: 'Nectarines'},
        {value: 'Noodle mix'},
        {value: 'Nuts'},
        {value: 'Oatmeal'},
        {value: 'Olive oil'},
        {value: 'Olives (black)'},
        {value: 'Olives (green)'},
        {value: 'Onions'},
        {value: 'Oranges'},
        {value: 'Oregano'},
        {value: 'Oysters'},
        {value: 'Pancake mix'},
        {value: 'Papaya'},
        {value: 'Paper plates'},
        {value: 'Paper towels'},
        {value: 'Paprika'},
        {value: 'Pasta'},
        {value: 'Pasta sauce'},
        {value: 'Pastries'},
        {value: 'Peaches'},
        {value: 'Peanut butter'},
        {value: 'Pears'},
        {value: 'Pepper'},
        {value: 'Peppers'},
        {value: 'Pickles'},
        {value: 'Pie'},
        {value: 'Pie crust'},
        {value: 'Pie filling'},
        {value: 'Pie shells'},
        {value: 'Pita bread'},
        {value: 'Pizza'},
        {value: 'Plastic bags'},
        {value: 'Plastic cutlery'},
        {value: 'Plastic wrap'},
        {value: 'Plums'},
        {value: 'Polish'},
        {value: 'Pomegranate'},
        {value: 'Popcorn'},
        {value: 'Poppy seed'},
        {value: 'Pork'},
        {value: 'Pot pies'},
        {value: 'Potato chips'},
        {value: 'Potatoes'},
        {value: 'Potatoes'},
        {value: 'Pretzels'},
        {value: 'Processed cheese'},
        {value: 'Pudding'},
        {value: 'Raisins'},
        {value: 'Razors/blades'},
        {value: 'Red pepper'},
        {value: 'Relish'},
        {value: 'Rice mix'},
        {value: 'Sage'},
        {value: 'Salad dressing'},
        {value: 'Salad greens'},
        {value: 'Salmon'},
        {value: 'Salsa'},
        {value: 'Salsa'},
        {value: 'Salt'},
        {value: 'Sausage'},
        {value: 'Seasoned salt'},
        {value: 'Seeds'},
        {value: 'Shampoo'},
        {value: 'Shampoo'},
        {value: 'Shaving cream'},
        {value: 'Shortening'},
        {value: 'Shredded cheese'},
        {value: 'Shrimp'},
        {value: 'Soft drinks'},
        {value: 'Soup'},
        {value: 'Soup mix'},
        {value: 'Sour cream'},
        {value: 'Soy sauce'},
        {value: 'Spaghetti'},
        {value: 'Spinach'},
        {value: 'Sponges'},
        {value: 'Sprouts'},
        {value: 'Squash'},
        {value: 'Steak'},
        {value: 'Steak sauce'},
        {value: 'Straws'},
        {value: 'Sugar'},
        {value: 'Sugar (brown)'},
        {value: 'Sugar (powdered)'},
        {value: 'Sunscreen'},
        {value: 'Sweet & sour'},
        {value: 'Swiss cheese'},
        {value: 'Tea'},
        {value: 'Teriyaki'},
        {value: 'Tilapia'},
        {value: 'Toilet tissue'},
        {value: 'Tomatoes'},
        {value: 'Toothbrush'},
        {value: 'Toothpaste'},
        {value: 'Tortilla chips'},
        {value: 'Tortillas (corn)'},
        {value: 'Tortillas (flour)'},
        {value: 'Treats'},
        {value: 'Tuna'},
        {value: 'Turkey'},
        {value: 'Tv dinners'},
        {value: 'Vacuum bags'},
        {value: 'Vanilla extract'},
        {value: 'Vegetable oil'},
        {value: 'Vegetables'},
        {value: 'Veggieburger'},
        {value: 'Vinegar'},
        {value: 'Waffles'},
        {value: 'Watermelon'},
        {value: 'Waxed paper'},
        {value: 'Whipped cream'},
        {value: 'White rice'},
        {value: 'Wine'},
        {value: 'Wipes'},
        {value: 'Yeast'},
        {value: 'Yogurt'},
        {value: 'Zucchini'},
];
